version: 4
mqtt:
  base_topic: zigbee
  server: mqtt://mosquitto:1883
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  channel: 11
  network_key:
    - 74
    - 45
    - 69
    - 58
    - 199
    - 223
    - 165
    - 179
    - 116
    - 4
    - 18
    - 83
    - 49
    - 61
    - 102
    - 150
  pan_id: 2547
  ext_pan_id:
    - 222
    - 58
    - 235
    - 180
    - 33
    - 205
    - 114
    - 252
frontend:
  enabled: true
  port: 8080
homeassistant:
  enabled: false

